config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  # Devise URLs

  devise_for :admins

  # Publish URLs

  match 'publish/create_publish_request', via: [:get, :post]
  match 'publish/metadata', via: [:get, :post]
  match 'publish/parse_match', via: [:get, :post]
  match 'publish/select_data', via: [:get, :post]

  get 'publish/first_check'
  get 'publish/accepted'
  get 'publish/end'

  match 'publish/generate_rd', via: [:get, :post]

  post 'publish/imp_q'

  # DataProduct URLs

  get 'data_product/show'
  get 'data_product/edit_metadata'

  post 'data_product/update_metadata'

  get 'data_product/edit_columns'

  post 'data_product/update_columns'
  post 'data_product/accept'
  post 'data_product/revoke'
end

app/controllers/publish_controller.rb
require 'json'
require 'nokogiri'
require 'fileutils'

class PublishController < ApplicationController
  before_action :authenticate_admin!, only: [:first_check, :accepted, :generate_rd, :final_check, :imp_q]

  def create_publish_request
    if request.get?
    end

    if request.post?
      begin

        # Create the resource_directory and write raw_data there

        dachs_directory = File.read('dachs_directory')

        uploaded_data = params[:data]

        schema = metadatum_params[:title].split(' ').first.downcase

        resource_directory = File.join(dachs_directory, schema)

        Dir.mkdir(resource_directory) unless File.exists?(resource_directory)

        Dir.mkdir(File.join(resource_directory, 'data')) unless File.exists?(File.join(resource_directory, 'data'))

        raw_data_path = File.join(resource_directory, 'data', uploaded_data.original_filename)

        File.open(raw_data_path, 'wb') do |file|
          file.write(uploaded_data.read)
        end

        # Create data_product and associated metadata

        raw_data_format = uploaded_data.original_filename.split('.').last

        data_product = DataProduct.create(status: 0, schema: schema, resource_directory: resource_directory, filename: File.join('data', uploaded_data.original_filename), format: raw_data_format, hdu_index: params[:hdu_index])

        data_product.metadatum = Metadatum.create(metadatum_params)

        redirect_to action: 'metadata', id: data_product.id
      rescue StandardError => error
        redirect_to publish_create_publish_request_path, flash: { alert: 'An error ocurred... Please be sure to fill in all the fields' }

        FileUtils.rm_r(resource_directory) if File.exists?(resource_directory)
      end
    end
  end

  def metadata
    if request.get?
      @data_product = DataProduct.find(params[:id])

      result = `python fits_metadata_parser.py #{File.join(@data_product.resource_directory, @data_product.filename)} #{@data_product.hdu_index}`
      
      metadata = JSON.parse(result)

      @creators = metadata['creator']
      @instrument = metadata['instrument']
      @facility = metadata['facility']

      @types = File.readlines('vocabulary/meta_types.txt').sort!
      @coverage_wavebands = File.readlines('vocabulary/meta_coverage_wavebands.txt').sort!
      @subjects = File.readlines('vocabulary/meta_subjects.txt').sort!
    end

    if request.post?
      begin
        # Update data_product and associated metadata

        @data_product = DataProduct.find(params[:data_product_id])

        subjects = metadatum_params[:subjects].reject { |s| s.empty? }.join(';')

        coverage_wavebands = metadatum_params[:coverage_wavebands].reject { |cw| cw.empty? }.join(';')

        types = metadatum_params[:types].reject { |ta| ta.empty? }.join(';')

        @data_product.metadatum.update_attributes(metadatum_params.except(:coverage_wavebands).except(:subjects).except(:types).merge(coverage_wavebands: coverage_wavebands).merge(subjects: subjects).merge(types: types))

        redirect_to action: 'select_data', id: @data_product.id
      rescue StandardError => error
        puts(error)
        redirect_to publish_metadata_path(id: @data_product_id.id), flash: { alert: 'An error ocurred... Please be sure to fill in all the fields' }
      end
    end
  end

  def select_data
    if request.get?
      @data_product = DataProduct.find(params[:id])

      result = `python fits_column_parser.py #{File.join(@data_product.resource_directory, @data_product.filename)} #{@data_product.hdu_index}`
      
      fits = JSON.parse(result)

      @columns = fits['columns']
    end

    if request.post?
      @data_product = DataProduct.find(params[:data_product_id])

      params[:columns].each_with_index { |val, index|
        @data_product.fits_columns.create(identifier: val)
      }

      redirect_to action: 'parse_match', id: @data_product.id
    end
  end

  def parse_match
    if request.get?
      @data_product = DataProduct.find(params[:id])

      @types = File.readlines('vocabulary/column_types.txt')

      result = `python fits_column_parser.py #{File.join(@data_product.resource_directory, @data_product.filename)} #{@data_product.hdu_index}`
      
      fits = JSON.parse(result)

      @columns = fits['columns'].insert(0, '')

      @raw_comments = fits['comments']
      @raw_formats = fits['formats']
      @raw_units = fits['units']
      @raw_ucds = fits['ucds']

      @units = fits['units'].uniq.sort  
      @ucds = fits['ucds'].uniq.sort
    end

    if request.post?
      params[:fits_column_id].each_with_index { |val, index|

        col = FitsColumn.find(val)
        
        col.update_attributes(name: params[:name][index], description: params[:description][index], type_alt: params[:type_alt][index], verb_level: params[:verb_level][index], unit: params[:unit][index], ucds: params[:ucds][index], required: params[:required][index])
      }

      redirect_to action: 'end'
    end
  end

  def end
  end

  def first_check
    @data_products = DataProduct.where(status: 0)
  end

  def accepted
    @data_products = DataProduct.where(status: 1)
  end

  def generate_rd
    if request.get?

      dachs_directory = File.read('dachs_directory')

      if dachs_directory == '/var/gavo/inputs'
        @can_publish = true
      end

      @data_products = DataProduct.where(status: 1)
    end

    if request.post?
      begin
        data_product = DataProduct.find(params[:id])

        file = File.new(File.join(data_product.resource_directory, 'q.rd'), 'wb')

        # Escribiendo el resource descriptor

        builder = Nokogiri::XML::Builder.new do |xml|
          xml.resource('schema' => "#{data_product.metadatum.title.split(' ').first.downcase}") do

            # Meta
            
            xml.meta('name' => 'title') { xml.text("#{data_product.metadatum.title}") }
            xml.meta('name' => 'description') { xml.text("#{data_product.metadatum.description}") }
            xml.meta('name' => 'creationDate') { xml.text("#{data_product.metadatum.created_at.strftime('%FT%T')}") }

            xml.meta('name' => 'creator') do
              xml.meta('name' => 'name') { xml.text("#{data_product.metadatum.creators}") }
            end

            data_product.metadatum.subjects.split(';').map(&:strip).each do |subject|
              xml.meta('name' => 'subject') { xml.text("#{subject}") }
            end

            data_product.metadatum.types.split(';').map(&:strip).each do |type|
              xml.meta('name' => 'type') { xml.text("#{type}") }
            end

            xml.meta('name' => 'facility') { xml.text("#{data_product.metadatum.facility}") }
            xml.meta('name' => 'instrument') { xml.text("#{data_product.metadatum.instrument}") }

            coverage_wavebands = data_product.metadatum.coverage_wavebands.split(';')

            if coverage_wavebands.length == 1
              xml.meta('name' => 'coverage.waveband') { xml.text("#{coverage_wavebands.first}") }
            else
              xml.meta('name' => 'coverage') do
                data_product.metadatum.coverage_wavebands.split(';').map(&:strip).each do |waveband|
                  xml.meta('name' => 'waveband') { xml.text("#{waveband}") }
                end
              end       
            end

            # Table

            # Verificamos si se encuentra RA y DEC dentro de las columnas, si estan entonces usamos el mixin SCS

            ra_presence = false
            dec_presence = false

            data_product.fits_columns.each do |col|
              ra_presence = true if col.ucds == 'pos.eq.ra;meta.main'
              dec_presence = true if col.ucds == 'pos.eq.dec;meta.main'
            end

            if ra_presence and dec_presence
              table_att = {'id' => 'main', 'onDisk' => 'True', 'adql' => 'True', 'mixin' => '//scs#q3cindex'}
            else
              table_att = {'id' => 'main', 'onDisk' => 'True', 'adql' => 'True'}
            end

            # Asumimos que solamente se agregan columnas de un solo HDU, en caso de que se quieran publicar columnas de diferentes HDUs (que problablemente tienen diferente cantidad de filas) es necesario definir mas de una tabla y hacer mas de un import

            xml.table(table_att) do
              data_product.fits_columns.each do |col|
                column_att = Hash.new

                column_att["name"] = "#{col.name}"
                column_att[:verbLevel] = "#{col.verb_level}"
                column_att[:type] = "#{col.type_alt}"
                column_att[:required] = "#{col.required.to_s.capitalize}"

                if not col.description.blank?
                  column_att[:description] = "#{col.description}"
                end

                if not col.unit.blank?
                  column_att[:unit] = "#{col.unit}"
                end

                if not col.ucds.blank?
                  column_att[:ucd] = "#{col.ucds}"
                end

                xml.column(column_att)
              end
            end

            xml.data('id' => 'import') do
              xml.sources { xml.text("#{data_product.filename}") }

              xml.fitsTableGrammar('hdu' => "#{data_product.hdu_index}")

              xml.make('table' => 'main') do
                xml.rowmaker do
                  data_product.fits_columns.each do |col|
                    xml.map('dest' => "#{col.name}") { xml.text("@#{col.identifier}") }
                  end
                end
              end
            end

            id_prescence = false
            id_col_name = nil

            data_product.fits_columns.each do |col|
              if col.ucds == 'meta.id;meta.main'
                id_prescence = true
                id_col_name = col.name
              end
            end

            if ra_presence and dec_presence and id_prescence
              shortname = data_product.metadatum.title.downcase.split.map(&:first).join

app/helpers/publish_helper.rb
module PublishHelper
end

app/views/publish/_column.html.erb
<p><h3>Column</h3></p>

<div class='form-group'>
	<%= label_tag :identifier %><br />
	<%= select_tag 'identifier[]', options_for_select(@columns), { id: "identifier-tmp", onchange: "identifier_selected(this.id)", class: "form-control" } %>
	<small class="form-text text-muted">The column identifier in your file.</small>
</div>
<div class='form-group'>
	<%= hidden_field_tag 'name[]', nil,  id: "name-tmp", class: 'form-control' %>
</div>
<div class='form-group'>
	<%= label_tag :description %><br />
	<%= text_field_tag 'description[]', nil, id: "description-tmp", class: 'form-control' %>
	<small class="form-text text-muted">A description for the data in this column.</small>
</div>
<div class='form-group'>
	<%= label_tag :type %><br />
	<%= select_tag 'type_alt[]', options_for_select(@types.map { |s| [s.strip] }), { id: "type-tmp", class: "form-control" } %>
	<small class="form-text text-muted">The data type of the data in this column.</small>
</div>
<div class='form-group'>
	<%= label_tag :verb_level %><br />
	<%= select_tag 'verb_level[]', options_for_select(1..30), class: 'form-control' %>
	<small class="form-text text-muted">The importance of the data in this column. 1 is very important, 30 is not important.</small>
</div>
<div class='form-group'>
	<%= label_tag :unit %> <a id="manual_unit-tmp" href="#" onclick="replace_manual_unit(this.id);return false;">(or manually write the unit)</a> <br />
	<%= select_tag 'unit[]', options_for_select(@units), { id: "unit-tmp", class: "form-control" } %>
	<small class="form-text text-muted">The unit of the data in this column.</small>
</div>
<div class='form-group'>
  <%= label_tag :UCDs, 'UCDs' %> <a id="manual_ucd-tmp" href="#" onclick="replace_manual_ucd(this.id);return false;">(or manually write the UCDs)</a> <br />
	<%= select_tag 'ucds[]', options_for_select(@ucds), { id: "ucds-tmp", class: "form-control" } %>
	<small class="form-text text-muted">The UCD of the data in this column.</small>
</div>
<div class='form-group'>
	<%= label_tag :required, 'Is this column required?' %><br />
	<%= select_tag 'required[]', options_for_select(['Yes', 'No']), class: 'form-control' %>
	<small class="form-text text-muted">If it's required, then there can't be nulls in this column.</small>
</div>

<hr />

app/views/publish/accepted.html.erb
<% if @data_products.length > 0 %>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Schema</th>      
      <th scope="col">Resource directory</th>
      <th scope="col">Filename</th>
      <th scope="col">Format</th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @data_products.each_with_index do |data_product, index| %>
    <tr>
      <th scope="row"><%= index + 1 %></th>
      <td><%= data_product.metadatum.title %></td>
      <td><%= data_product.schema %></td>
      <td><%= data_product.resource_directory %></td>
      <td><%= data_product.filename %></td>
      <td><%= data_product.format %></td>
      <td><%= link_to 'Show', data_product_show_path(id: data_product.id) %></td>
      <td><%= link_to 'Revoke', data_product_revoke_path(id: data_product.id), method: :post %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <br />
  <p class="text-center">There aren't accepted petitions.</p>
  <br />
<% end %>

app/views/publish/create_publish_request.html.erb
<h1 class="text-center">Basic Data Input</h1>
<br />
<div class="row">
	<div class="col-xs-10 col-xs-offset-1 text-center">
	  <ol class="progress-meter">
      <li class="progress-point todo">Basic Data Input</li>
      <li class="progress-point todo">General Metadata Input</li>
      <li class="progress-point todo">Select Data to publish</li>
	    <li class="progress-point todo">Data Metadata input</li>
	  </ol>
	</div>
</div>
<br />
<div class="row">
	<div class='col-xs-8 col-xs-offset-2'>
		<%= form_with url: publish_create_publish_request_path, local: true, method: :post do |form| %>
			<div class='form-group'>
				<%= form.label :title %><br />
				<%= form.text_field :title, class: 'form-control' %>
				<small class="form-text text-muted">A title for your dataset.</small>
			</div>
			<div class='form-group'>
				<%= form.label :description %><br />
				<%= form.text_area :description, class: 'form-control', size: '50x10' %>
				<small class="form-text text-muted">A description for your data.</small>
			</div>
			<div class='form-group'>
				<%= form.label :data %><br />
				<%= form.file_field :data %>
				<small class="form-text text-muted">Your data.</small>
			</div>
			<div class='form-group'>
				<%= form.label :hdu_index, 'HDU Index' %><br />
				<%= form.number_field :hdu_index, min: '0', class: "form-control" %>
				<small class="form-text text-muted">The HDU that you want to use.</small>
			</div>
			<div class='actions'>
				<br /><%= form.submit "Next" %>
			</div>
		<% end %>
	</div>
</div>

app/views/publish/end.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1 text-center">
    <ol class="progress-meter">
      <li class="progress-point done">Basic Data Input</li>
      <li class="progress-point done">General Metadata Input</li>
      <li class="progress-point done">Select Data to publish</li>
	    <li class="progress-point done">Data Metadata input</li>
    </ol>
  </div>
</div>
<br />
<div class="row">
	<p class="text-center">Thanks you for your request!, we will check it soon!</p>
</div>

app/views/publish/first_check.html.erb
<% if @data_products.length > 0 %>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Schema</th>      
      <th scope="col">Resource directory</th>
      <th scope="col">Filename</th>
      <th scope="col">Format</th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @data_products.each_with_index do |data_product, index| %>
    <tr>
      <th scope="row"><%= index + 1 %></th>
      <td><%= data_product.metadatum.title %></td>
      <td><%= data_product.schema %></td>
      <td><%= data_product.resource_directory %></td>
      <td><%= data_product.filename %></td>
      <td><%= data_product.format %></td>
      <td><%= link_to 'Show', data_product_show_path(id: data_product.id) %></td>
      <td><%= link_to 'Edit Metadata', data_product_edit_metadata_path(id: data_product.id) %></td>
      <td><%= link_to 'Edit Columns', data_product_edit_columns_path(id: data_product.id) %></td>
      <td><%= link_to 'Accept', data_product_accept_path(id: data_product.id), method: :post %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <br />
  <p class="text-center">There aren't new petitions.</p>
  <br />
<% end %>

app/views/publish/generate_rd.html.erb
<% if @data_products.length > 0 %>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Schema</th>      
      <th scope="col">Resource directory</th>
      <th scope="col">Filename</th>
      <th scope="col">Format</th>
      <th scope="col"></th>
      <th scope="col"></th>
      <% if @can_publish %>
      <th scope="col"></th>
      <th scope="col"></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
  <% @data_products.each_with_index do |data_product, index| %>
    <tr>
      <th scope="row"><%= index + 1 %></th>
      <td><%= data_product.metadatum.title %></td>
      <td><%= data_product.schema %></td>
      <td><%= data_product.resource_directory %></td>
      <td><%= data_product.filename %></td>
      <td><%= data_product.format %></td>
      <td><%= link_to 'Show', data_product_show_path(id: data_product.id) %></td>
      <td><%= link_to 'Generate resource descriptor', publish_generate_rd_path(id: data_product.id), method: :post %></td>
      <% if @can_publish %>
      <td><%= link_to 'Publish to the VO', publish_imp_q_path(id: data_product.id), method: :post %></td>
      <td><%= link_to 'Visit service', "http://localhost:8080/browse/#{data_product.schema}/q", target: :_blank %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <br />
  <p class="text-center">There aren't accepted petitions.</p>
  <br />
<% end %>

app/views/publish/metadata.html.erb
<h1 class="text-center">General Metadata Input</h1>
<br />
<div class="row">
	<div class="col-xs-10 col-xs-offset-1 text-center">
	  <ol class="progress-meter">
      <li class="progress-point done">Basic Data Input</li>
      <li class="progress-point todo">General Metadata Input</li>
      <li class="progress-point todo">Select Data to publish</li>
	    <li class="progress-point todo">Data Metadata input</li>
	  </ol>
	</div>
</div>
<br />
<div class="row">
	<div class='col-xs-8 col-xs-offset-2'>
		<%= form_with url: publish_metadata_path, local: true, method: :post do |form| %>
			<%= hidden_field_tag 'data_product_id', @data_product.id %>

			<div class='form-group'>
				<%= form.label :creators %> <br />
				<%= form.text_field :creators, value: @creators, class: 'form-control' %>
				<small class="form-text text-muted">The authors of the data, separated by semicolon.</small>
			</div>
			<div class='form-group'>
				<%= form.label :source %><br />
				<%= form.text_field :source, class: 'form-control' %>
				<small class="form-text text-muted">The paper associated whith the data, preferably in bibcode.</small>
			</div>
			<div class='form-group'>
				<%= form.label :subjects %><br />
				<%= form.select :subjects, options_for_select(@subjects.map { |s| [s.strip] }), {}, { multiple: true, class: "form-control selectpicker", "data-live-search" => "true" } %>
				<small class="form-text text-muted">The subjects to which the data belong.</small>
			</div>
			<div class='form-group'>
				<%= form.label :instrument %><br />
				<%= form.text_field :instrument, value: @instrument, class: 'form-control' %>
				<small class="form-text text-muted">The instrument that produced the data.</small>
			</div>
			<div class='form-group'>
				<%= form.label :facility %><br />
				<%= form.text_field :facility, value: @facility, class: 'form-control' %>
				<small class="form-text text-muted">The facility at which the data was taken.</small>
			</div>
			<div class='form-group'>
				<%= form.label :types %><br />
				<%= form.select :types, options_for_select(@types.map { |t| [t.strip] }), {}, { multiple: true, class: "form-control selectpicker", "data-live-search" => "true" } %>
				<small class="form-text text-muted">The type of the data.</small>
			</div>
			<div class='form-group'>
				<%= form.label :coverage_wavebands %><br />
				<%= form.select :coverage_wavebands, options_for_select(@coverage_wavebands.map { |cw| [cw.strip] }), {}, { multiple: true, class: "form-control selectpicker", "data-live-search" => "true" } %>
				<small class="form-text text-muted">The waveband to which the data belongs.</small>
			</div>
			<div class='actions'>
				<br /><%= form.submit "Next" %>
			</div>
		<% end %>
	</div>
</div>

app/views/publish/parse_match.html.erb
<h1 class="text-center">Data Metadata input</h1>
<br />
<div class="row">
  <div class="col-xs-10 col-xs-offset-1 text-center">
    <ol class="progress-meter">
      <li class="progress-point done">Basic Data Input</li>
      <li class="progress-point done">General Metadata Input</li>
      <li class="progress-point done">Select Data to publish</li>
      <li class="progress-point todo">Data Metadata input</li>
    </ol>
  </div>
</div>
<br />
<div class="row">
  <div class='col-xs-8 col-xs-offset-2'>
    <%= form_with url: publish_parse_match_path, local: true, method: :post do |form| %>
      <div id='column_set'>
        <% @data_product.fits_columns.each_with_index do |col, index| %>
          <p><h3><%= col.identifier %></h3></p>

          <%= hidden_field_tag("identifier[]", col.identifier, id: "identifier-#{index + 1}") %>

          <%= hidden_field_tag 'fits_column_id[]', col.id %>

          <div class='form-group'>
            <%= hidden_field_tag 'name[]', nil, id: "name-#{index + 1}", class: 'form-control' %>
          </div>

          <div class='form-group'>
            <%= label_tag :description %><br />
            <%= text_field_tag 'description[]', nil, id: "description-#{index + 1}", class: 'form-control' %>
            <small class="form-text text-muted">A description for the data in this column.</small>
          </div>
          <div class='form-group'>
            <%= label_tag :type %><br />
            <%= select_tag 'type_alt[]', options_for_select(@types.map { |s| [s.strip] }), { id: "type-#{index + 1}", class: "form-control" } %>
            <small class="form-text text-muted">The data type of the data in this column.</small>
          </div>
          <div class='form-group'>
            <%= label_tag :verb_level %><br />
            <%= select_tag 'verb_level[]', options_for_select(1..30), class: 'form-control' %>
            <small class="form-text text-muted">The importance of the data in this column. 1 is very important, 30 is not important.</small>
          </div>
          <div class='form-group'>
            <%= label_tag :unit %> <a id="manual_unit-1" href="#" onclick="replace_manual_unit(this.id);return false;">(or manually write the unit)</a> <br />
            <%= select_tag 'unit[]', options_for_select(@units), { id: "unit-#{index + 1}", class: "form-control" } %>
            <small class="form-text text-muted">The unit of the data in this column.</small>
          </div>
          <div class='form-group'>
            <%= label_tag :UCDs, 'UCDs' %> <a id="manual_ucd-1" href="#" onclick="replace_manual_ucd(this.id);return false;">(or manually write the UCDs)</a> <br />
            <%= select_tag 'ucds[]', options_for_select(@ucds), { id: "ucds-#{index + 1}", class: "form-control" } %>
            <small class="form-text text-muted">The UCD of the data in this column.</small>
          </div>
          <div class='form-group'>
            <%= label_tag :required, 'Is this column required?' %><br />
            <%= select_tag 'required[]', options_for_select([['Yes', true], ['No', false]]), class: 'form-control' %>
            <small class="form-text text-muted">If it's required, then there can't be nulls in this column.</small>
          </div>

          <hr />

        <% end %>
      </div>

      <div class='actions'>
        <br /><%= form.submit "Next" %>
      </div>
    <% end %>

    <div class="hide" id="new_column_form">
      <%= render partial: "column", locals: { skill: false } %>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    var columns_quantity = <%= @data_product.fits_columns.length %>

    var columns = <%= raw @columns.to_json %>
    
    raw_comments = <%= raw @raw_comments.to_json %>
    raw_formats = <%= raw @raw_formats.to_json %>
    raw_units = <%= raw @raw_units.to_json %>
    raw_ucds = <%= raw @raw_ucds.to_json %>

    unit_html = document.getElementById("unit-tmp").outerHTML
    ucds_html = document.getElementById("ucds-tmp").outerHTML

    for (var i = 1; i < columns_quantity + 1; i++) {
      set_metadata(i, columns)
    }
  })

  function set_metadata(place_num, columns) {
    column_index = place_num

    identifier = document.getElementById(`identifier-${column_index}`).value

    selected_index = columns.indexOf(identifier);

    document.getElementById(`name-${column_index}`).value = identifier.toLowerCase()

    document.getElementById(`description-${column_index}`).value = raw_comments[selected_index - 1]
    document.getElementById(`type-${column_index}`).value = raw_formats[selected_index - 1]

    if (raw_units[selected_index - 1]) {
      $(`#unit-${column_index}`).replaceWith(unit_html.replace('unit-tmp', `unit-${column_index}`))

      document.getElementById(`unit-${column_index}`).value = raw_units[selected_index - 1]
    } else
      $(`#unit-${column_index}`).replaceWith(`<input type='text' name='unit[]'' id='unit-${column_index}' class='form-control' />`)

    if (raw_ucds[selected_index - 1]) {
      $(`#ucds-${column_index}`).replaceWith(ucds_html.replace('ucds-tmp', `ucds-${column_index}`))

      document.getElementById(`ucds-${column_index}`).value = raw_ucds[selected_index - 1]
    }
    else
      $(`#ucds-${column_index}`).replaceWith(`<input type='text' name='ucds[]'' id='ucds-${column_index}' class='form-control' />`)
  }

  function replace_manual_unit(id) {
    var column = id.split("-")

    var column_index = parseInt(column[column.length - 1])

    $(`#unit-${column_index}`).replaceWith(`<input type='text' name='unit[]'' id='unit-${column_index}' class='form-control' />`)
  }

  function replace_manual_ucd(id) {
    var column = id.split("-")

    var column_index = parseInt(column[column.length - 1])

    $(`#ucds-${column_index}`).replaceWith(`<input type='text' name='ucds[]'' id='ucds-${column_index}' class='form-control' />`)
  }
</script>

app/views/publish/select_data.html.erb
<h1 class="text-center">Select Data to publish</h1>
<br />
<div class="row">
  <div class="col-xs-10 col-xs-offset-1 text-center">
    <ol class="progress-meter">
      <li class="progress-point done">Basic Data Input</li>
      <li class="progress-point done">General Metadata Input</li>
      <li class="progress-point todo">Select Data to publish</li>
      <li class="progress-point todo">Data Metadata input</li>
    </ol>
  </div>
</div>
<br />
<div class="row">
  <div class="row">
    <div class='col-xs-10 col-xs-offset-1'>
      <p class="text-center">In order to be able to use the SCS protocol in your data, it's necessary that at least you provide positional data, with pos.eq.ra;meta.main and pos.eq.dec;meta.main UCDs, and a third column that acts as an identifier with the meta.id;meta.main UCD</p>
    </div>
  </div>
  <br />
  <div class="row">
    <div class='col-xs-4 col-xs-offset-4'>
      <%= form_with url: publish_select_data_path, local: true, method: :post do |form| %>
        <%= hidden_field_tag 'data_product_id', @data_product.id %>

        <%= select_tag 'columns', options_for_select(@columns), { id: "columns-select", multiple: true, class: "form-control" } %>

        <div class='actions'>
          <br /><%= form.submit "Next" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

  <script type="text/javascript">$('#columns-select').multiSelect()</script>