config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  # Devise URLs

  devise_for :admins

  # Publish URLs

  match 'publish/create_publish_request', via: [:get, :post]
  match 'publish/metadata', via: [:get, :post]
  match 'publish/parse_match', via: [:get, :post]
  match 'publish/select_data', via: [:get, :post]

  get 'publish/first_check'
  get 'publish/accepted'
  get 'publish/end'

  match 'publish/generate_rd', via: [:get, :post]

  post 'publish/imp_q'

  # DataProduct URLs

  get 'data_product/show'
  get 'data_product/edit_metadata'

  post 'data_product/update_metadata'

  get 'data_product/edit_columns'

  post 'data_product/update_columns'
  post 'data_product/accept'
  post 'data_product/revoke'
end

app/models/data_product.rb
class DataProduct < ApplicationRecord
	has_one :metadatum, dependent: :delete
	has_many :fits_columns, dependent: :delete_all

	validates :status, presence: true
	validates :schema, presence: true
	validates :resource_directory, presence: true
	validates :filename, presence: true
	validates :format, presence: true
end

app/controllers/data_product_controller.rb
class DataProductController < ApplicationController
	before_action :set_data_product, only: [:accept, :revoke, :show, :update, :edit_metadata, :edit_columns]
	before_action :authenticate_admin!, except: [:show]

	def accept
		@data_product.update_attribute('status', 1)

		redirect_to publish_first_check_path
	end

	def revoke
		@data_product.update_attribute('status', 0)

		redirect_to publish_accepted_path
	end

	def edit_metadata
		@types = File.readlines('vocabulary/meta_types.txt').sort!
		@coverage_wavebands = File.readlines('vocabulary/meta_coverage_wavebands.txt').sort!
		@subjects = File.readlines('vocabulary/meta_subjects.txt').sort!
	end

	def edit_columns
		@types = File.readlines('vocabulary/column_types.txt')

		result = `python fits_column_parser.py #{File.join(@data_product.resource_directory, @data_product.filename)} #{@data_product.hdu_index}`

		fits = JSON.parse(result)

		@columns = fits['columns'].insert(0, '')

		@raw_comments = fits['comments']
		@raw_formats = fits['formats']
		@raw_units = fits['units']
		@raw_ucds = fits['ucds']

		@units = fits['units'].uniq.sort  
		@ucds = fits['ucds'].uniq.sort
	end

	def update_metadata
		data_product = DataProduct.find(params[:data_product_id])

		if metadatum_params[:title] != data_product.metadatum.title
			begin
				dachs_directory = File.read('dachs_directory')

				schema = metadatum_params[:title].split(' ').first.downcase

				resource_directory = File.join(dachs_directory, schema)

				File.delete(File.join(resource_directory, 'q.rd')) if File.exist?(File.join(resource_directory, 'q.rd'))

				File.rename(data_product.resource_directory, resource_directory)

				data_product.update_attributes(schema: schema, resource_directory: resource_directory)

				subjects = metadatum_params[:subjects].reject { |s| s.empty? }.join(';')

				coverage_wavebands = metadatum_params[:coverage_wavebands].reject { |cw| cw.empty? }.join(';')

				types = metadatum_params[:types].reject { |ta| ta.empty? }.join(';')

				data_product.update_attribute('hdu_index', params[:hdu_index])

				data_product.metadatum.update_attributes(metadatum_params.except(:coverage_wavebands).except(:subjects).except(:types).merge(coverage_wavebands: coverage_wavebands).merge(subjects: subjects).merge(types: types))
		
				redirect_to data_product_show_path(id: data_product.id), notice: 'Se actualizaron los datos'
      rescue StandardError => error
        redirect_to publish_metadata_path, flash: { alert: 'An error ocurred... Please be sure to fill in all the fields' }

        FileUtils.rm_r(resource_directory) if File.exists?(resource_directory)
      end
		else
			subjects = metadatum_params[:subjects].reject { |s| s.empty? }.join(';')

			coverage_wavebands = metadatum_params[:coverage_wavebands].reject { |cw| cw.empty? }.join(';')

			types = metadatum_params[:types].reject { |ta| ta.empty? }.join(';')

			data_product.update_attribute('hdu_index', params[:hdu_index])

			data_product.metadatum.update_attributes(metadatum_params.except(:coverage_wavebands).except(:subjects).except(:types).merge(coverage_wavebands: coverage_wavebands).merge(subjects: subjects).merge(types: types))
	
			redirect_to data_product_show_path(id: data_product.id), notice: 'Se actualizaron los datos'
		end
	end

	def update_columns
		params[:fits_column_id].each_with_index { |val, index|

			col = FitsColumn.find(val)
			
			col.update_attributes(identifier: params[:identifier][index], name: params[:name][index], description: params[:description][index], type_alt: params[:type_alt][index], verb_level: params[:verb_level][index], unit: params[:unit][index], ucds: params[:ucds][index], required: params[:required][index])
		}

		redirect_to data_product_show_path(id: params[:id]), notice: 'Se actualizaron los datos'
	end

  def show
  end

  private

	  def set_data_product
	  	@data_product = DataProduct.find(params[:id])
	  end

    def metadatum_params
      params.permit(:title, :description, :creators, :instrument, :facility, :source, types: [], subjects: [], coverage_wavebands: [])
    end
end

app/helpers/data_product_helper.rb
module DataProductHelper
end

app/views/data_product/_column.html.erb
<p><h3>Column</h3></p>

<div class='form-group'>
	<%= label_tag :identifier %><br />
	<%= select_tag 'identifier[]', options_for_select(@columns), { id: "identifier-tmp", onchange: "identifier_selected(this.id)", class: "form-control" } %>
	<small class="form-text text-muted">The column identifier in your file.</small>
</div>
<div class='form-group'>
	<%= hidden_field_tag 'name[]', nil,  id: "name-tmp", class: 'form-control' %>
</div>
<div class='form-group'>
	<%= label_tag :description %><br />
	<%= text_field_tag 'description[]', nil, id: "description-tmp", class: 'form-control' %>
	<small class="form-text text-muted">A description for the data in this column.</small>
</div>
<div class='form-group'>
	<%= label_tag :type %><br />
	<%= select_tag 'type_alt[]', options_for_select(@types.map { |s| [s.strip] }), { id: "type-tmp", class: "form-control" } %>
	<small class="form-text text-muted">The data type of the data in this column.</small>
</div>
<div class='form-group'>
	<%= label_tag :verb_level %><br />
	<%= select_tag 'verb_level[]', options_for_select(1..30), class: 'form-control' %>
	<small class="form-text text-muted">The importance of the data in this column. 1 is very important, 30 is not important.</small>
</div>
<div class='form-group'>
	<%= label_tag :unit %> <a id="manual_unit-tmp" href="#" onclick="replace_manual_unit(this.id);return false;">(or manually write the unit)</a> <br />
	<%= select_tag 'unit[]', options_for_select(@units), { id: "unit-tmp", class: "form-control" } %>
	<small class="form-text text-muted">The unit of the data in this column.</small>
</div>
<div class='form-group'>
  <%= label_tag :UCDs, 'UCDs' %> <a id="manual_ucd-tmp" href="#" onclick="replace_manual_ucd(this.id);return false;">(or manually write the UCDs)</a> <br />
	<%= select_tag 'ucds[]', options_for_select(@ucds), { id: "ucds-tmp", class: "form-control" } %>
	<small class="form-text text-muted">The UCD of the data in this column.</small>
</div>
<div class='form-group'>
	<%= label_tag :required, 'Is this column required?' %><br />
	<%= select_tag 'required[]', options_for_select(['Yes', 'No']), class: 'form-control' %>
	<small class="form-text text-muted">If it's required, then there can't be nulls in this column.</small>
</div>

<hr />

app/views/data_product/edit_columns.html.erb
<p class="text-center">Para que se pueda usar el protocolo SCS a los datos subidos es necesario que al menos se seleccionen tres columnas, dos con los datos de las posiciones, es decir, RA (con UCD pos.eq.ra;meta.main), DEC (con UCD pos.eq.dec;meta.main) y otra columna que actue como un identificador (con UCD meta.id;meta.main)</p>

<br />

<div class='col-xs-8 col-xs-offset-2'>
  <%= form_with url: data_product_update_columns_path, local: true, method: :post do |form| %>

    <%= hidden_field_tag 'id', "#{@data_product.id}" %>

    <div id='column_set'>
      <% @data_product.fits_columns.each_with_index do |col, index| %>
        <p><h3>Column</h3></p>

        <%= hidden_field_tag 'fits_column_id[]', col.id %>

        <div class='form-group'>
          <%= label_tag :identifier %><br />
          <%= select_tag 'identifier[]', options_for_select(@columns, col.identifier), { id: "identifier-#{index + 1}", onchange: "identifier_selected(this.id)", class: "form-control" } %>
          <small class="form-text text-muted">The column identifier in your file.</small>
        </div>
        <div class='form-group'>
          <%= hidden_field_tag 'name[]', nil, value: col.name, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= label_tag :description %><br />
          <%= text_field_tag 'description[]', nil, value: col.description, id: "description-#{index + 1}", class: 'form-control' %>
          <small class="form-text text-muted">A description for the data in this column.</small>
        </div>
        <div class='form-group'>
          <%= label_tag :type %><br />
          <%= select_tag 'type_alt[]', options_for_select(@types.map { |s| [s.strip] }, col.type_alt), { id: "type-#{index + 1}", class: "form-control" } %>
          <small class="form-text text-muted">The data type of the data in this column.</small>
        </div>
        <div class='form-group'>
          <%= label_tag :verb_level %><br />
          <%= select_tag 'verb_level[]', options_for_select(1..30, col.verb_level), class: 'form-control' %>
          <small class="form-text text-muted">The importance of the data in this column. 1 is very important, 30 is not important.</small>
        </div>
        <div class='form-group'>
          <%= label_tag :unit %> <a id=<%= "manual_unit-#{index + 1}" %> href="#" onclick="replace_manual_unit(this.id);return false;">(or manually write the unit)</a> <br />
          <%= select_tag 'unit[]', options_for_select(@units, col.unit), { id: "unit-#{index + 1}", class: "form-control" } %>
          <small class="form-text text-muted">The unit of the data in this column.</small>
        </div>
        <div class='form-group'>
          <%= label_tag :UCDs, 'UCDs' %> <a id=<%= "manual_ucd-#{index + 1}" %> href="#" onclick="replace_manual_ucd(this.id);return false;">(or manually write the UCDs)</a> <br />
          <%= select_tag 'ucds[]', options_for_select(@ucds, col.ucds), { id: "ucds-#{index + 1}", class: "form-control" } %>
          <small class="form-text text-muted">The UCD of the data in this column.</small>
        </div>
        <div class='form-group'>
          <%= label_tag :required, 'Is this column required?' %><br />
          <%= select_tag 'required[]', options_for_select([['Yes', true], ['No', false]], col.required), class: 'form-control' %>
          <small class="form-text text-muted">If it's required, then there can't be nulls in this column.</small>
        </div>

        <hr />

      <% end %>
    </div>

    <div class='actions'>
      <br /><%= form.submit %>
    </div>
  <% end %>

  <div class="hide" id="new_column_form">
    <%= render partial: "column", locals: { skill: false } %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
  	var columns_quantity = <%= @data_product.fits_columns.length %>

    columns = <%= raw @columns.to_json %>

    raw_comments = <%= raw @raw_comments.to_json %>
    raw_formats = <%= raw @raw_formats.to_json %>
    raw_units = <%= raw @raw_units.to_json %>
    raw_ucds = <%= raw @raw_ucds.to_json %>

    col_comments = <%= raw @data_product.fits_columns.pluck(:description) %>
    col_formats = <%= raw @data_product.fits_columns.pluck(:type_alt) %>
    col_units = <%= raw @data_product.fits_columns.pluck(:unit) %>
    col_ucds = <%= raw @data_product.fits_columns.pluck(:ucds) %>

    unit_html = document.getElementById("unit-tmp").outerHTML
    ucds_html = document.getElementById("ucds-tmp").outerHTML

    for (i = 0; i < columns_quantity; i++)
    	identifier_selected(`identifier-${i+1}`)
  })

  function identifier_selected(id) {
    column = id.split("-")

    column_index = parseInt(column[column.length - 1])
    selected_index = document.getElementById(id).selectedIndex

    if (raw_units[selected_index - 1] && raw_units.indexOf(col_units[column_index - 1]) > -1 ) {
      $(`#unit-${column_index}`).replaceWith(unit_html.replace('unit-tmp', `unit-${column_index}`))

      document.getElementById(`unit-${column_index}`).value = raw_units[selected_index - 1]
    } else
      $(`#unit-${column_index}`).replaceWith(`<input type='text' name='unit[]'' id='unit-${column_index}' value='${col_units[column_index - 1]}' class='form-control' />`)

    if (raw_ucds[selected_index - 1] && raw_ucds.indexOf(col_ucds[column_index - 1]) > -1 ) {
      $(`#ucds-${column_index}`).replaceWith(ucds_html.replace('ucds-tmp', `ucds-${column_index}`))

      document.getElementById(`ucds-${column_index}`).value = raw_ucds[selected_index - 1]
    }
    else
      $(`#ucds-${column_index}`).replaceWith(`<input type='text' name='ucds[]'' id='ucds-${column_index}' value='${col_ucds[column_index - 1]}' class='form-control' />`)
  }

  function replace_manual_unit(id) {
    column = id.split("-")

    column_index = parseInt(column[column.length - 1])

    $(`#unit-${column_index}`).replaceWith(`<input type='text' name='unit[]'' id='unit-${column_index}' class='form-control' />`)
  }

  function replace_manual_ucd(id) {
    column = id.split("-")

    column_index = parseInt(column[column.length - 1])

    $(`#ucds-${column_index}`).replaceWith(`<input type='text' name='ucds[]'' id='ucds-${column_index}' class='form-control' />`)
  }
</script>

app/views/data_product/edit_metadata.html.erb
<div class='col-xs-8 col-xs-offset-2'>
	<%= form_with url: data_product_update_metadata_path, local: true, method: :post do |form| %>
		<%= hidden_field_tag 'data_product_id', @data_product.id %>
		<div class='form-group'>
			<%= form.label :title %><br />
			<%= form.text_field :title, class: 'form-control', value: @data_product.metadatum.title %>
			<small class="form-text text-muted">A title for your dataset.</small>
		</div>
		<div class='form-group'>
			<%= form.label :description %><br />
			<%= form.text_area :description, class: 'form-control', size: '50x10', value: @data_product.metadatum.description %>
			<small class="form-text text-muted">A description for your data.</small>
		</div>
		<div class='form-group'>
			<%= form.label :creators %><br />
			<%= form.text_field :creators, class: 'form-control', value: @data_product.metadatum.creators %>
			<small class="form-text text-muted">The authors of the data, separated by semicolon.</small>
		</div>
		<div class='form-group'>
			<%= form.label :source %><br />
			<%= form.text_field :source, class: 'form-control', value: @data_product.metadatum.source %>
			<small class="form-text text-muted">From where the data belongs.</small>
		</div>
		<div class='form-group'>
			<%= form.label :subjects %><br />
			<%= form.select :subjects, options_for_select(@subjects.map { |s| [s.strip] }, @data_product.metadatum.subjects.split(';')), {}, { multiple: true, class: "form-control selectpicker", "data-live-search" => "true" } %>
			<small class="form-text text-muted">The subjects to which the data belong.</small>
		</div>
		<div class='form-group'>
			<%= form.label :instrument %><br />
			<%= form.text_field :instrument, class: 'form-control', value: @data_product.metadatum.instrument %>
			<small class="form-text text-muted">The instrument that produced the data.</small>
		</div>
		<div class='form-group'>
			<%= form.label :facility %><br />
			<%= form.text_field :facility, class: 'form-control', value: @data_product.metadatum.facility %>
			<small class="form-text text-muted">The facility at which the data was taken.</small>
		</div>
		<div class='form-group'>
			<%= form.label :types %><br />
			<%= form.select :types, options_for_select(@types.map { |t| [t.strip] }, @data_product.metadatum.types.split(';')), {}, { multiple: true, class: "form-control selectpicker", "data-live-search" => "true" } %>
			<small class="form-text text-muted">The type of the data.</small>
		</div>
		<div class='form-group'>
			<%= form.label :coverage_wavebands %><br />
			<%= form.select :coverage_wavebands, options_for_select(@coverage_wavebands.map { |cw| [cw.strip] }, @data_product.metadatum.coverage_wavebands.split(';')), {}, { multiple: true, class: "form-control selectpicker", "data-live-search" => "true" } %>
			<small class="form-text text-muted">The waveband to which the data belongs.</small>
		</div>
		<div class='form-group'>
			<%= form.label :hdu_index, 'HDU Index' %><br />
			<%= form.number_field :hdu_index, value: @data_product.hdu_index, min: '0', class: "form-control" %>
			<small class="form-text text-muted">The HDU that you want to use.</small>
		</div>
		<div class='actions'>
			<br /><%= form.submit %>
		</div>
	<% end %>
</div>

app/views/data_product/show.html.erb
<h1 align='center'><%= @data_product.metadatum.title %></h1>

<hr />

<h2>Data Product</h2>

<p><strong>Schema</strong>: <%= @data_product.schema %></p>
<p><strong>Resource directory</strong>: <%= @data_product.resource_directory %></p>
<p><strong>Filename</strong>: <%= @data_product.filename %></p>
<p><strong>Format</strong>: <%= @data_product.format %></p>
<p><strong>HDU Index</strong>: <%= @data_product.hdu_index %></p>

<hr />

<h2>Metadata</h2>

<p><strong>Description</strong>: <%= @data_product.metadatum.description %></p>
<p><strong>Creation date</strong>: <%= @data_product.metadatum.created_at %></p>
<p><strong>Creators</strong>: <%= @data_product.metadatum.creators %></p>
<p><strong>Subjects</strong>: <%= @data_product.metadatum.subjects %></p>
<p><strong>Instrument</strong>: <%= @data_product.metadatum.instrument %></p>
<p><strong>Facility</strong>: <%= @data_product.metadatum.facility %></p>
<p><strong>Type</strong>: <%= @data_product.metadatum.types %></p>
<p><strong>Coverage waveband</strong>: <%= @data_product.metadatum.coverage_wavebands %></p>

<hr />

<h2>Columns</h2>

<% @data_product.fits_columns.each do |col| %>
	<h4><strong><%= col.name %></strong> (<small><%= col.identifier %> in FITS</small>)</h4>
	
	<% if not col.description.blank? %>
	<p><strong>Description</strong>: <%=  col.description %></p>
	<% end %>

	<p><strong>Type</strong>: <%=  col.type_alt %></p>
	<p><strong>Verb</strong>: <%=  col.verb_level %></p>

	<% if not col.unit.blank? %>
	<p><strong>Unit</strong>: <%=  col.unit %></p>
	<% end %>

	<% if not col.unit.blank? %>
	<p><strong>UCDs</strong>: <%=  col.ucds %></p>
	<% end %>
	
	<p><strong>Required</strong>: <%=  col.required %></p>
	<br />
<% end %>