config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  # Devise URLs

  devise_for :admins

  # Publish URLs

  match 'publish/create_publish_request', via: [:get, :post]
  match 'publish/metadata', via: [:get, :post]
  match 'publish/parse_match', via: [:get, :post]
  match 'publish/select_data', via: [:get, :post]

  get 'publish/first_check'
  get 'publish/accepted'
  get 'publish/end'

  match 'publish/generate_rd', via: [:get, :post]

  post 'publish/imp_q'

  # DataProduct URLs

  get 'data_product/show'
  get 'data_product/edit_metadata'

  post 'data_product/update_metadata'

  get 'data_product/edit_columns'

  post 'data_product/update_columns'
  post 'data_product/accept'
  post 'data_product/revoke'
end

app/views/layouts/_navbar.html.erb
<nav class='navbar navbar-default'>
  <div class='container-fluid'>
    <div class='navbar-header'>
      <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#bs-example-navbar-collapse-1' aria-expanded='false'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <%= link_to 'ChiVO', root_path, class: 'navbar-brand' %>
    </div>

    <div class='collapse navbar-collapse' id='bs-example-navbar-collapse-1'>
      <ul class='nav navbar-nav navbar-right'>
        <% if admin_signed_in? %>
        <li class='dropdown'>
          <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-haspopup='true' aria-expanded='false'>Menu <span class='caret'></span></a>
          <ul class='dropdown-menu'>
            <li><%= link_to 'Revisar peticiones de publicaciones', publish_first_check_path %></li>
            <li><%= link_to 'Peticiones de publicaciones aceptadas', publish_accepted_path %></li>
            <li role='separator' class='divider'></li>
            <li><%= link_to 'Generar resource descriptor', publish_generate_rd_path %></li>
          </ul>
        </li>
        <li><%= link_to('Logout', destroy_admin_session_path, method: :delete) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PublishDataVo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <!-- JQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>

    <!-- Bootstrap -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    
    <!-- Bootstrap Select -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/js/bootstrap-select.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/css/bootstrap-select.min.css">

    <!-- Multi Select -->
    <script src="https://rawgit.com/lou/multi-select/master/js/jquery.multi-select.js"></script>
    <link rel="stylesheet" href="https://rawgit.com/lou/multi-select/master/css/multi-select.css">
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <% if notice %>
    <p class="alert alert-success" align="center"><%= notice %></p>
    <% elsif alert %>
    <p class="alert alert-danger" align="center"><%= alert %></p>
    <% end %>

  	<div class='container-fluid'>
      <div class="panel panel-default col-xs-10 col-xs-offset-1">
        <div class="panel-body">
          <br />

  		    <%= yield %>
          
        </div>
      </div>
  	</div>
  </body>
</html>